apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    cert-manager.io/issue-temporary-certificate: "false"
spec:
  tls:
    - secretName: {{ .Values.ingress.secret }}
      hosts:
      {{- range $host := .Values.ingress.frontend.hosts }}
      - {{ $host }}
      {{- end }}
      {{- range $host := .Values.ingress.images.hosts }}
      - {{ $host }}
      {{- end }}
  rules:
  {{- range $host := .Values.ingress.frontend.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.service.name }}
            port:
              number: {{ $.Values.service.port }}
  {{- end }}
  {{- range $host := .Values.ingress.images.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: {{ $.Values.ingress.images.path | default "/public/images" }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.service.name }}
            port:
              number: {{ $.Values.service.port }}
  {{- end }}
